import logging
from indicators.indicators import get_crypto_symbols_from_env, get_indicators
from telegram.alert import send_telegram_message

logging.basicConfig(level=logging.INFO)

def run():
    symbols = get_crypto_symbols_from_env()
    for symbol in symbols:
        try:
            indicators = get_indicators(symbol)
            if indicators is None:
                logging.warning(f"Could not fetch {symbol} indicators. Skipping message.")
                continue
            message = f"""
            📈 *{symbol.replace('USDT','')} Update*

            🧠 *Weekly Indicators:*
            - RSI: {indicators['RSI']}
            - MACD: {indicators['MACD']}
            - Stochastic: {indicators['Stochastic']}
            - BB: {indicators['BB']}
            - SMA20: {indicators['SMA20']}
            - EMA50: {indicators['EMA50']}
            - VWAP: {indicators['VWAP']}
            - ADX: {indicators['ADX']}
            - ATR: {indicators['ATR']}
            - OBV: {indicators['OBV']}

            📊 *Outlook:* _Auto-generated by strategy logic_
            """
            try:
                send_telegram_message(message)
                logging.info(f"Sent Telegram message for {symbol}")
            except Exception as e:
                logging.error(f"Failed to send Telegram message for {symbol}: {e}")
        except Exception as e:
            logging.error(f"Error processing {symbol}: {e}")
