name: Run Python Script

on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours UTC
  workflow_dispatch: # Allow manual run

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.20"

      - name: Clear pip cache
        run: pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          CRYPTOS: ${{ secrets.CRYPTOS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COIN_DESK_API_KEY: ${{ secrets.COIN_DESK_API_KEY }}
        run: python main.py
